{
 "title": "no test",
 "description": "Docker Monitoring Template With Service Filter",
 "tags": [ "docker" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "service", "query": "api_joinserver_request_count" }
  ]
 },
 "panels": [
  {
   "title": "gateway connect count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "backend_semtechudp_gateway_connect_count"
    }
   ]
  },
  {
   "title": "received count",
   "type": "graph",
   "description": "The number of UDP packets received by the backend (per packet_type)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "backend_semtechudp_udp_received_count",
     "legendFormat": "{{semtechudp_udp_received_count}}"
    }
   ]
  },
  {
   "title": "Sent count ",
   "type": "graph",
   "description": "The number of UDP packets sent by the backend (per packet_type)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "backend_semtechudp_udp_sent_count",
     "legendFormat": "{{ backend_semtechudp_udp_sent_count }}"
    }
   ]
  },
  {
   "title": "mqtt command count  ",
   "type": "graph",
   "description": "The number of published commands by the MQTT backend (per command).",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "backend_mqtt_command_count ",
     "legendFormat": "{{ backend_semtechudp_udp_sent_count }}"
    }
   ]
  },
  {
   "title": "mqtt event count  ",
   "type": "graph",
   "description": "The number of received events by the MQTT backend (per event type)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "backend_mqtt_event_count ", "legendFormat": "{{ mqtt event count }}" }
   ]
  },
  {
   "title": "Join request",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "api_joinserver_request_count", "legendFormat": "{{ joinrequest count  }}" },
    { "expr": "api_joinserver_request_count" }
   ]
  }
 ]
}